package com.muqui.corona.model;
// Generated 22/07/2017 12:25:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Partido generated by hbm2java
 */
@Entity
@Table(name="partido"
    ,catalog="partido"
)
public class Partido  implements java.io.Serializable {


     private Integer id;
     private String local;
     private int goleslocal;
     private String visita;
     private int golesvista;
     private String estadio;
     private Date fecha;
     private String jornada;
     private String torneo;
     private String fechaTemporal;

    public Partido() {
    }

	
    public Partido(int goleslocal, int golesvista) {
        this.goleslocal = goleslocal;
        this.golesvista = golesvista;
    }
    public Partido(String local, int goleslocal, String visita, int golesvista, String estadio, Date fecha, String jornada, String torneo) {
       this.local = local;
       this.goleslocal = goleslocal;
       this.visita = visita;
       this.golesvista = golesvista;
       this.estadio = estadio;
       this.fecha = fecha;
       this.jornada = jornada;
       this.torneo = torneo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="local", length=45)
    public String getLocal() {
        return this.local;
    }
    
    public void setLocal(String local) {
        this.local = local;
    }

    
    @Column(name="goleslocal", nullable=false)
    public int getGoleslocal() {
        return this.goleslocal;
    }
    
    public void setGoleslocal(int goleslocal) {
        this.goleslocal = goleslocal;
    }

    
    @Column(name="visita", length=45)
    public String getVisita() {
        return this.visita;
    }
    
    public void setVisita(String visita) {
        this.visita = visita;
    }

    
    @Column(name="golesvista", nullable=false)
    public int getGolesvista() {
        return this.golesvista;
    }
    
    public void setGolesvista(int golesvista) {
        this.golesvista = golesvista;
    }

    
    @Column(name="estadio", length=45)
    public String getEstadio() {
        return this.estadio;
    }
    
    public void setEstadio(String estadio) {
        this.estadio = estadio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="jornada", length=45)
    public String getJornada() {
        return this.jornada;
    }
    
    public void setJornada(String jornada) {
        this.jornada = jornada;
    }

    
    @Column(name="torneo", length=45)
    public String getTorneo() {
        return this.torneo;
    }
    
    public void setTorneo(String torneo) {
        this.torneo = torneo;
    }

    /**
     * @return the fechaTemporal
     */
    @Transient
    public String getFechaTemporal() {
        return fechaTemporal;
    }

    /**
     * @param fechaTemporal the fechaTemporal to set
     */
    public void setFechaTemporal(String fechaTemporal) {
        this.fechaTemporal = fechaTemporal;
    }




}


